; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:nodemcuv2-base]
platform = espressif8266
board = nodemcuv2
framework = arduino

; Serial monitor settings
monitor_speed = 115200

; Library dependencies (auto downloaded from PlatformIO Registry)
lib_deps = 
    tzapu/WiFiManager@^2.0.17

; Build flags (preprocessor definitions)
build_flags = 
    -I include          ; needed so platformIO knows where to find ota_config.h


[env:nodemcuv2-release]
extends = env:nodemcuv2-base
build_type = release

build_flags = 
    ${env:nodemcuv2-base.build_flags}
    -D FIRMWARE_VERSION=\"${sysenv.FIRMWARE_VERSION}\"
    -D GIT_COMMIT_HASH=\"${sysenv.GIT_COMMIT_HASH}\"
    -D BUILD_TIMESTAMP=\"${sysenv.BUILD_TIMESTAMP}\"


[env:nodemcuv2-debug]
extends = env:nodemcuv2-base
build_type = debug

build_flags = 
    ${env:nodemcuv2-base.build_flags}
    -D SERIAL_DEBUG
    -D FIRMWARE_VERSION=\"debugBuild\"
    -D GIT_COMMIT_HASH=\"0a1b2c_dummy-hash\"
    -D BUILD_TIMESTAMP=\"19700101-101010\"
    -D OTA_CHECK_INTERVAL_MS=${sysenv.OTA_CHECK_INTERVAL_MS}

[env:native]
platform = native
lib_compat_mode = strict
build_flags = 
    -I include
    -D NATIVE_TEST_BUILD

    